baseURL = "https://shunfenglee.github.io/"
languageCode = "zh-tw"
defaultContentLanguage = "zh"
title = "ShunFeng's Blog"
theme = "dream"

enableGitInfo = true
enableRobotsTXT = true

hasCJKLanguage = true

[services]
[services.disqus]
shortname = "shunfenglee"
[services.googleAnalytics]
ID = "G-QC18RE2BVS"

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

[params]
lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "/me/background.jpg"
# backgroundImageDark = ""

images = ["me/background.jpg"]

author = "ShunFeng"
description = "Life is pessimism, but pessimism is not everything."
# #頭像源自FB xlink:href
avatar = "https://scontent.ftpe8-3.fna.fbcdn.net/v/t39.30808-1/441525809_8319418528073153_6553555876227541548_n.jpg?stp=dst-jpg_p200x200&_nc_cat=107&ccb=1-7&_nc_sid=0ecb9b&_nc_ohc=UrJ_6R8I8sEQ7kNvgFnZNTT&_nc_ht=scontent.ftpe8-3.fna&oh=00_AYBUuzO-2rgF1UdPus1uhK0G3I0-R2crwwDoUdu5ftv8bw&oe=66A1B284"
headerTitle = "ShunFeng's Blog"
motto = "生活即是厭世，厭世不是全部。"

# footerBottomText = ""

rss = true

utterancesRepo = "gshunfenglee/shunfenglee.github.io"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""

email = "leoshunfeng@gmail.com.com"

siteStartYear = 2024

favicon = "/favicon.ico"

# Syntax highlighting
customSyntaxHighlighting = true

# options
stickyNav = true
showSummaryCoverInPost = true
# hasTwitterEmbed = true

[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MMM月dd日"
# jsDateFormat = "yyyy年MM月dd日，cccc"
